version: "3.9"

services:
  flask:
    build:
      context: flask
      dockerfile: Dockerfile
    container_name: info910_flask
    environment:
      - APP_NAME=INFO910-Conseils
    expose:
      - 8080
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: info910_nginx
    ports:
      - "80:80"
