apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: chatshttp
    role: front
spec:
  selector:
    matchLabels:
      app: api
      role: front
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
        role: front
    spec:
      containers:
      - name: flask
        image: info910/info910-api
        resources:
          limits:
            memory: "350Mi"
            cpu: "500m"
          requests:
            memory: "200Mi"
            cpu: "0.3"
        ports:
        - containerPort: 8080
        env:
        - name: APP_NAME
          value: INFO910-Conseils
